spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#logging:
#  level:
#    com.neha.springbootgithubjenkinsdocker.controller: DEBUG



  #JPA Settings
  jpa.hibernate.ddl-auto: create

management:
  endpoints:
    web:
      exposure:
        include: "health, beans, metrics"
      base-path: "/management-dashboard"

  endpoint:
    health:
      show-details: always
server:
  port: 1234

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9095/eureka/